### PR TITLE
[WIP]cloudlfare adapter wip

### PR DESCRIPTION
**Pull request by AlemTuzlak**
# Description

 Work in progress for cloudflare adapter.

### CODE REVIEW

**Comment by AdiRishi** [comment]
Just want to say, really keen for this. I've just discovered remix and this repository. All my stuff is completely built on Cloudflare pages, can't wait to use these devtools :)

**Comment by AlemTuzlak** [comment]
@AdiRishi i am so happy to hear that! Well maybe it isn't clear but you CAN use the CLIENT part fwith cloudflare just fine, it's the server part you can't. I am working on an adapter that will bring as much functionality as possible to the server side part.

**Comment by DanPete** [comment]
Hey @AlemTuzlak! Thanks for the awesome work here. Would this PR help to allow [Hydrogen](https://github.com/Shopify/hydrogen) to use the dev tools?

Right now, I seem to be getting a lot of errors trying to run this with the custom server directions, but also possible that I'm not setting it up correctly.

Hydrogen uses Mini-Oxygen for dev environment which is base off of cloudflare, I think.

Here are some of the errors, I'm getting trying to put dev tools in Hydrodens' `server.ts` file:

<details>
<summary>Errors</summary>

```
 [ERROR] Could not resolve "http"

    ../node_modules/ws/lib/websocket.js:7:21:
      7 │ const http = require('http');
        ╵                      ~~~~~~

  The package "http" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


✘ [ERROR] Could not resolve "net"

    ../node_modules/ws/lib/websocket.js:8:20:
      8 │ const net = require('net');
        ╵                     ~~~~~

  The package "net" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


✘ [ERROR] Could not resolve "tls"

    ../node_modules/ws/lib/websocket.js:9:20:
      9 │ const tls = require('tls');
        ╵                     ~~~~~

  The package "tls" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


✘ [ERROR] Could not resolve "crypto"

    ../node_modules/ws/lib/websocket.js:10:44:
      10 │ const { randomBytes, createHash } = require('crypto');
         ╵                                             ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


✘ [ERROR] Could not resolve "stream"

    ../node_modules/ws/lib/websocket.js:11:37:
      11 │ const { Duplex, Readable } = require('stream');
         │                                      ~~~~~~~~
         ╵                                      "./stream"

  The package "stream" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


✘ [ERROR] Could not resolve "url"

    ../node_modules/ws/lib/websocket.js:12:24:
      12 │ const { URL } = require('url');
         ╵                         ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
  ```
  </details>
  
 But Hydrogen dev server requires the `serverPlatform` to be set to ` 'neutral'`.

**Comment by AlemTuzlak** [comment]
@DanPete hey Dan! Thank you for reaching out, I have actually run a lot of testing here with cloudflare and running them in a wrangler env with node but there is a lot at play here that stops this from happening. I believe once the remix team releases cloudflare support with Vite the dev tools will automatically work there without any issues. I don't know if that would help with Hydrogen support?

I have put this on hold to see what happens when Vite comes into the picture and they deprecate the old compiler but would love to hear if that would still cause issues for hydrogen, although it's important to note that the client side can run anywhere

**Comment by DanPete** [comment]
@AlemTuzlak Thanks for the hint about client side being able to run anywhere! That's exactly what I was doing wrong. 🤦 

I was thinking I had to follow the [Custom Server Setup](https://github.com/Code-Forge-Net/Remix-Dev-Tools?tab=readme-ov-file#custom-server-setup) to get it working properly.

But once I re-read the README, I got it working correctly with Hydrogen! 🙂

**Comment by AlemTuzlak** [comment]
@DanPete that is awesome to hear! no worries, I plan on making a video and a docs site pretty soon to avoid these issues, the github readme is not really the best place for all of this info

**Comment by AlemTuzlak** [comment]
Remix Dev tools work with cloudflare on Vite, closing this branch!

**Pull request closed without merging**
